# Generated by Django 3.2 on 2022-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/', verbose_name='Content media url'),
        ),
    ]
