# Generated by Django 3.2 on 2022-05-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_content_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_title', models.CharField(max_length=150, unique=True)),
                ('season_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Contents(ex. Movies,Cartoon,Documentary etc.)'},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='slug',
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_title',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contents.season'),
            preserve_default=False,
        ),
    ]
