# Generated by Django 3.2 on 2022-05-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_episode_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_ar', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('descriptions', models.TextField()),
                ('release_year', models.CharField(help_text='Enter Release Year', max_length=5)),
                ('runtime', models.CharField(help_text='Runtime must be in minutes', max_length=15)),
                ('video_quality', models.CharField(choices=[('full_hd', 'Full HD'), ('hd', 'HD'), ('sd', 'SD')], default='full_hd', max_length=8)),
                ('audience_age', models.PositiveIntegerField(default=13)),
                ('country', models.ManyToManyField(related_name='tvseries', to='contents.Country')),
                ('genre', models.ManyToManyField(related_name='tvseries', to='contents.Genre')),
            ],
            options={
                'verbose_name_plural': ' Tv Series',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='tv_series',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='contents.tvseries'),
            preserve_default=False,
        ),
    ]
