# Generated by Django 3.2 on 2022-05-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20220523_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='runtime',
            field=models.CharField(blank=True, help_text='Runtime must be in minutes', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='runtime',
            field=models.CharField(blank=True, help_text='Runtime must be in minutes', max_length=15, null=True),
        ),
    ]
