# Generated by Django 3.2 on 2022-06-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_auto_20220612_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='country',
            field=models.ManyToManyField(related_name='contents', to='contents.Country'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.ManyToManyField(related_name='contents', to='contents.Genre'),
        ),
    ]
