# Generated by Django 3.2 on 2022-06-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_auto_20220612_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cover_photos',
            field=models.ImageField(default=None, upload_to='uploads/movies/% Y/% m/% d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvseries',
            name='cover_photos',
            field=models.ImageField(default=1, upload_to='uploads/movies/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
