# Generated by Django 3.2 on 2022-06-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_auto_20220612_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cover_photo',
            field=models.ImageField(upload_to='movies/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='cover_photo',
            field=models.ImageField(upload_to='movies/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='ContentGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.ImageField(upload_to='movies/%Y/%m/%d/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.content')),
            ],
        ),
    ]
