# Generated by Django 3.2 on 2022-06-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_auto_20220616_0646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentgallery',
            options={'verbose_name': 'Content Gallery', 'verbose_name_plural': 'Content Gallery'},
        ),
    ]
