# Generated by Django 3.2 on 2022-07-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_tvseriesgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseriesgallery',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.tvseries'),
        ),
    ]
