# Generated by Django 3.2 on 2022-07-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_alter_tvseriesgallery_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseries',
            name='cover_photo',
            field=models.ImageField(upload_to='tvseries/%Y/%m/%d/'),
        ),
    ]
