# Generated by Django 3.2 on 2022-07-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_alter_tvseries_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cover_photo',
            field=models.ImageField(upload_to='contents/%Y/%m/%d/'),
        ),
    ]
